{% set name = "ablang2" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ablang2-{{ version }}.tar.gz
  sha256: 7f01bec5c5a5d5c270fa078cdd923d3a98bdc2b93538b17d46231db2d783676d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch >=1.9
    - requests
    - einops
    - rotary-embedding-torch
    - numpy
    - fsspec

test:
  imports:
    - ablang2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'AbLang2: An antibody-specific language model focusing on NGL prediction.'
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/TobiasHeOl/AbLang2

extra:
  recipe-maintainers:
    - mbestipa
